@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Oct 25 15:24:48 +0200 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim with_select_TB_behav -key {Behavioral:sim_1:Functional:with_select_TB} -tclbatch with_select_TB.tcl -view E:/TUK_Summer2023/Sep 08_2023/Vhdl_eduvance/lab3_with_select/with_select_TB_behav.wcfg -log simulate.log"
call xsim  with_select_TB_behav -key {Behavioral:sim_1:Functional:with_select_TB} -tclbatch with_select_TB.tcl -view E:/TUK_Summer2023/Sep 08_2023/Vhdl_eduvance/lab3_with_select/with_select_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
