webtalk_init -webtalk_dir E:/TUK_Summer2023/Sep 08_2023/Vhdl_eduvance/lab3_with_select/lab3_with_select.sim/sim_1/behav/xsim/xsim.dir/with_select_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 25 15:25:42 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "548e9f22-cf5f-44ed-b36e-507ad391e292" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "71bb03aeaa9c4d99a73c8f15ffd8eaff" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7752_KB" -context "xsim\\usage"
webtalk_transmit -clientid 27861281 -regid "" -xml E:/TUK_Summer2023/Sep 08_2023/Vhdl_eduvance/lab3_with_select/lab3_with_select.sim/sim_1/behav/xsim/xsim.dir/with_select_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/TUK_Summer2023/Sep 08_2023/Vhdl_eduvance/lab3_with_select/lab3_with_select.sim/sim_1/behav/xsim/xsim.dir/with_select_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/TUK_Summer2023/Sep 08_2023/Vhdl_eduvance/lab3_with_select/lab3_with_select.sim/sim_1/behav/xsim/xsim.dir/with_select_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
